ALTER TABLE "patients" ADD COLUMN IF NOT EXISTS "pregnancy_duration_weeks" INTEGER;
ALTER TABLE "patients" ADD COLUMN IF NOT EXISTS "breastfeeding_infant_age" VARCHAR(100);
ALTER TABLE "patients" ADD COLUMN IF NOT EXISTS "breastfeeding_type" VARCHAR(50);

ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "substance_duration" VARCHAR(100);
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "substance_last_use" VARCHAR(100);
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "substance_withdrawal_signs" BOOLEAN DEFAULT false;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "smoking_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "alcohol_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "toxic_exposure" BOOLEAN DEFAULT false;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "toxic_exposure_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "fasting_symptoms" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "night_shift_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "physical_activity_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "diet_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "hydration_notes" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "stress_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "sleep_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "sun_exposure_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "restrictive_diet_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "natural_products_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "blood_donation_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "sudden_medication_stop_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "medical_followup_status" VARCHAR(50);
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "last_consultation" VARCHAR(100);
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "self_diagnosis_treatments" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "hidden_self_medication" BOOLEAN DEFAULT false;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "hidden_self_medication_details" TEXT;
ALTER TABLE "patient_lifestyle" ADD COLUMN IF NOT EXISTS "phytotherapy_details" TEXT;
